### ISSUE TITLE
About the Jacobian impl reference

### ISSUE THREAD

**Issue by JzHuai0108** [VIS4ROB-lab/HyperState#8]
Hi David,

I am baffled by the [recursive Jacobians here](https://github.com/VIS4ROB-lab/HyperState/blob/main/internal/hyper/state/interpolators/spatial/su2.cpp#L71-#L143).
Is it implemented following C. Sommer et al [Efficient derivative computation paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Sommer_Efficient_Derivative_Computation_for_Cumulative_B-Splines_on_Lie_Groups_CVPR_2020_paper.pdf)?

Regards,

**Comment by McEmzi** [comment]
@JzHuai0108 Yes, in general, it follows the implementation by Sommer et al. However, we modified it to some degree to allow in-place computations/updates (entailing the propagation of summation terms). It also differs in the sense that Sommer et al. claim that their implementation is O(n), whereas ours trades in in-place computations against O(n^2) complexity (i.e., due to propagating the increments in every iteration), which should be insignificant for small spline orders in any case. Could you elaborate on which part is unclear?

Also, please feel free to have a look at the [Hyperion](https://github.com/VIS4ROB-lab/hyperion) framework, which entirely automates the generation of spline-related residuals, making our implementation (from this repository) as well as the one from Sommer et al. somewhat obsolete.

Please also note that the development on HyperSLAM-related repositories has largely been discontinued.
